# configs/loftr/drone_finetune.yaml

#################################
# 1) TRAINER hyper-parameters  #
#################################
TRAINER:
  # Base LR and optimizer
  CANONICAL_LR: 0.008
  OPTIMIZER: "adamw"
  ADAMW_DECAY: 0.1

  # Warmup schedule: first 1875 steps (≈3 epochs on your small set)
  WARMUP_STEP: 1875
  WARMUP_RATIO: 0.1

  # Multi-step LR schedule (epoch numbers)
  MSLR_MILESTONES: [8, 12, 16, 20, 24]

  # RANSAC threshold for pose metrics
  RANSAC_PIXEL_THR: 0.5

  # Epipolar-error threshold (for loss weighting / metrics)
  EPI_ERR_THR: 0.0005

  # Gradient clipping (norm)
  GRADIENT_CLIPPING: 0.0

#################################
#   2) MODEL—LoFTR Settings     #
#################################
LOFTR:
  # Downsampling ratio for coarse→fine
  RESOLUTION: [8, 1]

  # Fine‐search window (must be even)
  FINE_WINDOW_SIZE: 8

  # Align corners in interpolation?
  ALIGN_CORNER: False

  # Mixed-precision matching?
  MP: True

  # Replace any NaNs in attention scores
  REPLACE_NAN: True

  # Repeat eval N times (for stable pose‐AUC)
  EVAL_TIMES: 5

  ### Coarse-stage tweaks
  COARSE:
    # Turn off FlashAttention for determinism/timing
    NO_FLASH: True
    # “Number‐of‐points‐exported” grid sizes at each stage
    NPE: [832, 832, 832, 832]

  MATCH_COARSE:
    # Matching threshold
    THR: 0.2
    # Only supervise/train on this fraction of coarse points
    TRAIN_COARSE_PERCENT: 0.3
    # Use sparse ground‐truth supervision
    SPARSE_SPVS: True
    # fp16-optimized matmul? (usually off for correctness)
    FP16MATMUL: False

  MATCH_FINE:
    # Temperature and slice‐dim for local regression
    LOCAL_REGRESS_TEMPERATURE: 10.0
    LOCAL_REGRESS_SLICEDIM: 8

  ### Loss-stage tweaks
  LOSS:
    # Fine‐level loss type
    FINE_TYPE: "l2"           # choices: 'l2' or 'l2_with_std'
    # Weight the overlap term in coarse / fine losses?
    COARSE_OVERLAP_WEIGHT: True
    FINE_OVERLAP_WEIGHT: True
    # Local offset‐regression weight
    LOCAL_WEIGHT: 0.25

#################################
#   3) DATASET & I/O Settings   #
#################################
DATASET:
  # Don't cast images to fp16
  FP16: False

  # If you resize images in the pipeline, set here (default 832)
  MGDPT_IMG_RESIZE: 832
